[TAS-213] 写真削除機能の追加 (WIP)
MyGourmet/My_Gourmet pull request #115
Opened 2024-10-17 14:41 UTC by Ituking

## 関連のタスク issue

https://www.notion.so/masakisato/e089fa075c0344e1a1fa5f31442ac716
## 対応したこと

- 写真詳細ページのFirestoreの削除関数および、UIのコードを実装。

## 未解決事項
  

- テスト未実施
## 実際の挙動
  

## チェックリスト
  
- [ ] 実装完了後、問題が起こっていないか実際に動作確認したか  
- [ ] 補足があった方が良い/重点的にレビューが欲しい箇所にGitHub上でコメントをしたか

## その他コメント

このプルリクは、10/17のMTGで議題に上がっていたphoto_detail_page.dartのFutureProvider化
およびコンポーネント化のプルリクです。
- ブランチ名を `feat/TAS-213-photo-delete` から `feat/photo-delete` に変更しました。
- トラッキング設定の更新も完了しています。
- 既存のドラフトPRを利用して引き続きレビューをお願いします。

2024-10-17 23:11 UTC, masa-tokyo reviewed
@Ituking 

ドラフトPRありがとうございます！
現状のステータス的には、[こちらの受け入れ条件](https://www.notion.so/masakisato/e089fa075c0344e1a1fa5f31442ac716)を満たしているけどFutureProvider部分をリファクタリングしていく予定（昨日のお話だけで分からない箇所あればご相談ください）、という感じでしょうか？

また、レビュー依頼時には以下の２項目も埋めてもらうようお願いします🙏
![CleanShot 2024-10-18 at 08 01 08@2x](https://github.com/user-attachments/assets/0bf98ef7-ef06-415c-af58-7efe2e7c35bb)

2024-10-18 14:32 UTC, schwarzwald0906 commented on ios/Podfile.lock
> -COCOAPODS: 1.15.2
@Ituking 
手元で下記のコマンド打ってもらってもいいですか？
` pod --version`
僕の手元だと、1.15.2になります。
おそらく、itukingさんの手元のバージョンが古いのが原因かと。
`IPHONEOS_DEPLOYMENT_TARGET`
も軽く調べた感じ、上記に付随するっぽいです。

2024-10-19 03:27 UTC, Ituking commented on ios/Podfile.lock
> -COCOAPODS: 1.15.2
> @Ituking 手元で下記のコマンド打ってもらってもいいですか？ ` pod --version` 僕の手元だと、1.15.2になります。 おそらく、itukingさんの手元のバージョンが古いのが原因かと。 `IPHONEOS_DEPLOYMENT_TARGET` も軽く調べた感じ、上記に付随するっぽいです。

@schwarzwald0906 
```
pod --version
```
をしたところ、1.14.3だったのでCocoaPods のアップデートしてビルドします。
```
sudo gem install cocoapods
```
をして1.15.2になること確認しました。

2024-10-19 06:14 UTC, masa-tokyo reviewed
@Ituking 
先ほどコミットいただいたgit管理関連の件についてコメントしました！
アプリの機能の件が一通り出来たらまたお声がけください！
（その際はPRをDraft状態からOpenにしてもらって大丈夫です）

2024-10-19 06:14 UTC, masa-tokyo commented on .gitignore
> +obfuscate/ios/XCBuildData/
![badge](https://img.shields.io/badge/review-ask-blue.svg) 

こちらの変更の背景お聞きしたいです！
こちらのディレクトリ内には、難読化用オプション入れてリリース対応する際しか何か入ることは無いかなと思う（それもCodemagicで行うので基本不要ですが） & `obfuscate`全体をignoreしていたのはAndroid側のことも踏まえてでした！

2024-10-19 06:14 UTC, masa-tokyo commented on ios/build/.gitignore
> +ios/XCBuildData/
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg) 

上記のobfuscateと同様こちらも状況確認できたらと思います！
おそらく、プロジェクトのルートでは無い箇所で`flutter build ios`コマンド叩いちゃってるような気がします👀

2024-10-19 06:14 UTC, masa-tokyo commented on ios/build/.gitignore
> +ios/XCBuildData/
https://github.com/MyGourmet/My_Gourmet/pull/106#discussion_r1773522281

2024-10-19 06:14 UTC, masa-tokyo commented on ios/build/.gitignore
> +ios/XCBuildData/
以前金さんにも起こっていた上記の現象と同じかなと思います！

2024-10-19 06:27 UTC, masa-tokyo commented on ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
![badge](https://img.shields.io/badge/review-ask-blue.svg) 

こちらの差分も一旦戻してもらった上で pod バージョンが1.15.2の状態でも発生するか確認お願いしても良いでしょうか🙏 

Podfile上でiosバージョンは13に指定しているので、ここミスマッチ起きていそうなのが気になってます、

2024-10-19 06:27 UTC, masa-tokyo commented on ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
ちなみに、僕自身もこの辺り全然詳しい訳でも無いので、分からないことあったらこんな感じに雑にChatGPTに相談しながら考えたりしてます：

https://chatgpt.com/share/671350ab-5608-8003-a94b-c69d4ac49114

2024-10-19 06:32 UTC, Ituking commented on .gitignore
> +obfuscate/ios/XCBuildData/
@masa-tokyo

お疲れ様です。

### iOSビルドキャッシュのディレクトリを `.gitignore` に追加した背景
#### キャッシュファイルの管理方針
キャッシュファイルはビルド時に各開発者の環境で自動生成され、再生成が可能なものです。そのため、Gitでバージョン管理する必要がないと判断し、誤ってコミットしないための防止策として `.gitignore` に追加しました。

#### 作業経緯
Gitのステータスを確認した際に、`ios/XCBuildData/` 配下のキャッシュファイルが **Untracked** で表示されていたため、コミット対象から除外する目的で `.gitignore` に追加しています。

#### ご指摘への対応について
難読化のためのビルドに関しては **Codemagic** が管理する、という点についての認識が不足していました。  
もし、この変更が不要であれば、`.gitignore` の修正を削除し、適切な形に戻します。

以上、よろしくお願いします。

2024-10-19 06:41 UTC, Ituking commented on ios/build/.gitignore
> +ios/XCBuildData/
@masa-tokyo 

こちらの問題ですが、masakiさんの言うとおり
プロジェクトのルートでは無い箇所でflutter build iosコマンド叩いちゃいました。すみません🙏

2024-10-19 07:52 UTC, masa-tokyo commented on .gitignore
> +obfuscate/ios/XCBuildData/
@Ituking 

https://github.com/MyGourmet/My_Gourmet/pull/115#discussion_r1807207318
上記のコメントでお話されているように、`obfuscate`とは無縁な話そうですね！

![badge](https://img.shields.io/badge/review-must-red.svg) 
以下コミットにある、プロジェクトルートの`.gitignore`自体は必要なのでここで発生した差分だけ戻してもらうようにお願いします！
https://github.com/MyGourmet/My_Gourmet/pull/115/commits/57a4ddf11e08db7630fd4eac73ab1c541394775e

2024-10-19 08:47 UTC, Ituking commented
@masa-tokyo 

masakiさんからの指摘事項は全て修正しました。
一旦、写真削除機能をシミュレーター上で試すためにdevへマージをお願いしたいです！

2024-10-19 08:58 UTC, schwarzwald0906 commented
> @masa-tokyo
> 
> masakiさんからの指摘事項は全て修正しました。 一旦、写真削除機能をシミュレーター上で試すためにdevへマージさせてください。

@Ituking 
お疲れ様です。修正ありがとうございます！
こちらでも書いたように、マージしなくても検証できます。
よろしくお願いします 🙏 

https://flutteruniv.slack.com/archives/C06CBUPRQ1M/p1729319798497209?thread_ts=1729318369.503679&cid=C06CBUPRQ1M

2024-10-19 09:34 UTC, Ituking commented
@masa-tokyo 
ありがとうございます😊
Kimさんからの返信見れてませんでした…

2024-10-20 00:38 UTC, schwarzwald0906 commented
> * [ ]  実装完了後、問題が起こっていないか実際に動作確認したか
> * [ ]  補足があった方が良い/重点的にレビューが欲しい箇所にGitHub上でコメントをしたか

@Ituking 
こちらのチェックもお願いします。
[ ]の空白を消して、`x`でチェックできます。

2024-10-20 07:04 UTC, schwarzwald0906 requested changes

2024-10-20 07:04 UTC, schwarzwald0906 commented on lib/features/root_page.dart
>            }
前提として、自分がコミットした変更差分のみが表示されるようにして欲しいです。
レビュアーからすると、なぜここを変更したのか、混乱するからです。

この部分は、僕のコミットですよね。
![CleanShot 2024-10-20 at 15 50 23](https://github.com/user-attachments/assets/af7c9722-6033-4e4e-a708-bc86136f279e)

すでに、devには反映されています。
https://github.com/MyGourmet/My_Gourmet/blob/dev/lib/features/root_page.dart

自分のコミット以外のコミットは、原則含めないようにしてください。

やり方がわからなかったら聞いてください。
あと、そもそもなぜ最新ブランチで変更されているものが、ここで差分として出ているのかなども、一度調べてわからなかったら聞いてください。
「git rebase」などで出てくると思います。
どうしても難しかったら次回からで問題ないです。

2024-10-20 15:52 UTC, Ituking commented on lib/features/root_page.dart
>            }
@schwarzwald0906 
cc: @aru-gone2002  

ご指摘ありがとうございます！混乱を招いてしまい、すみません。  
今回、Kimさんのコミットがブランチに混ざってしまった原因を確認しました。  

---

### 次回から気をつけること
- **最新の `dev` ブランチから新しくブランチを切る**  
- **作業中もこまめに `rebase` して履歴を整理する**  

もし他に気になる点があれば教えてください！  

---

今回はこのまま進めさせていただきますが、次回からは同じことが起きないように気をつけます。  
よろしくお願いします🙇‍♂️

2024-10-21 23:00 UTC, masa-tokyo reviewed
@Ituking 

ご対応ありがとうございます！
こちらコメントしたのでご確認お願いします！

2024-10-21 23:00 UTC, masa-tokyo commented on lib/features/photo/photo_detail/photo_detail_page.dart
> +    final isEditing = ref.watch(photoDetailControllerProvider);
flutter_hooksの使い方については、ご自身でも調べてみてもらえたらと思うのですが、[こちらの過去のリファクタリング例](https://github.com/MyGourmet/My_Gourmet/pull/103/files#:~:text=lib/core/widgets/navigation_frame.dart)のようにすると、HookWidget & useState利用でいわゆるStatefulWidgetの`setState`のようなことが出来るのでご参考ください！

2024-10-21 23:00 UTC, masa-tokyo commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return Stack(
![badge](https://img.shields.io/badge/review-ask-blue.svg) 

こちらの差分の背景お聞きしたいです！
`showCardBack`プロパティを無くしてStackが追加されていますが、現状何も重なっていないように見えます👀
もし意図なく変更してしまっていたら戻してもらうようお願いします！

2024-10-21 23:15 UTC, schwarzwald0906 approved these changes

2024-10-21 23:15 UTC, schwarzwald0906 commented on lib/features/root_page.dart
>            }
@Ituking 
OKです！LGTMです。

@masa-tokyo 
他に何かありますか？

2024-10-22 15:43 UTC, Ituking commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return Stack(
@masa-tokyo

レビューありがとうございます！

当時のStack導入理由としては、編集時に画像の上にゴミ箱アイコンを重ねる意図がありました。
しかし、不要なStackが残ってしまっていたようです。

ご指摘の通り、現在はこのStackは不要です。
本来であれば、編集モード時にゴミ箱アイコンが画像の上に表示されるべきだったため、この部分は削除します。

引き続きよろしくお願いいたします！🙏

2024-10-23 01:03 UTC, Ituking commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return Stack(
@masa-tokyo
Stack を削除し、FlipCard を直接返すようにリファクタリングしました。
正常に動作することを確認済みですので、再度ご確認をお願いします🙏

2024-10-23 01:55 UTC, Ituking commented on lib/features/photo/photo_detail/photo_detail_page.dart
> +    final isEditing = ref.watch(photoDetailControllerProvider);
@masa-tokyo 

レビューありがとうございます！
確かに、Provider はより広範囲な状態管理に向いている一方で、
flutter_hooks はローカルな一時的な状態管理に適していることがよく分かりました。
（flutter_hooks を使った開発経験がなかったので、今回のご指摘で学ぶことができました…！）

また、useState を使った修正後のコードは、以前の実装に比べてシンプルで読みやすくなったと感じています。
修正も完了しましたので、引き続きレビューをよろしくお願いいたします！

2024-10-23 22:56 UTC, masa-tokyo reviewed
@Ituking 

コメントしました！

2024-10-23 22:56 UTC, masa-tokyo commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return FlipCard(
![badge](https://img.shields.io/badge/review-ask-blue.svg) 

差分見ると`showCardBack`が消えていますが、こちら削除した背景あればお聞きしたいです。
これは好みもあると思いますが、こういった変更の背景はコミット履歴に書いておくと、
- 自分で考えが整理出来る
- 後からgit履歴を見返した時に参考になる
のようなメリットもあるのかなと個人的には思ってます！

2024-10-23 22:56 UTC, masa-tokyo commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return FlipCard(
こんな感じです：
![CleanShot 2024-10-24 at 07 54 34@2x](https://github.com/user-attachments/assets/a7dd2711-a56b-40a2-9d18-59e5a299e634)
https://qiita.com/itosho/items/9565c6ad2ffc24c09364#%E5%8E%9F%E5%89%87

2024-10-23 22:56 UTC, masa-tokyo commented on lib/features/photo/photo_detail/photo_detail_controller.dart
![badge](https://img.shields.io/badge/review-must-red.svg) 

このファイルも消しましょう！

2024-10-24 01:00 UTC, Ituking commented on lib/features/photo/photo_detail/photo_detail_controller.dart
@masa-tokyo 

消そうと思っていたのですが、消し忘れてコミットしてしまいました。
すみません🙏

2024-10-24 01:46 UTC, masa-tokyo commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return FlipCard(
@schwarzwald0906 @aru-gone2002 @finish-cloud 
コミットメッセージについてはあまりルール的なもの決めてなかったのですが、ざっくり上記のように思ってます！
別の考え方も全然あると思うので、何かあったらご意見もらえたら嬉しいです🙌

2024-10-24 22:57 UTC, masa-tokyo commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return FlipCard(
@Ituking 
>差分見るとshowCardBackが消えていますが、こちら削除した背景あればお聞きしたいです。

あれ、こちらご回答お願いします！

2024-10-26 23:27 UTC, schwarzwald0906 commented
@masa-tokyo 
お疲れ様です。
これって今どうなっています？？

2024-10-27 00:09 UTC, masa-tokyo commented
https://github.com/MyGourmet/My_Gourmet/pull/115#discussion_r1815790107

2024-10-27 00:09 UTC, masa-tokyo commented
@schwarzwald0906 @Ituking 
上記で止まっちゃってますね、！

2024-10-27 03:13 UTC, Ituking commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return FlipCard(
@masa-tokyo

レビューありがとうございます！

今回、`PhotoDetailPage` では **`flutter_hooks` の `useState`** を使って `isEditing` の状態を管理するように実装しています。  
これにより、**ページ内の一時的な状態をシンプルに管理**できるようになっています。

---

### `showCardBack` 削除の背景

- `showCardBack` は **FlipCard の裏面を表示するかどうか**を制御するためのフラグでした。
- しかし、`isEditing` フラグと **役割が重複・干渉** しており、どちらがどの状態を管理すべきかが曖昧になる懸念がありました。
- 実装上も、FlipCard の **表裏を常に切り替え可能な状態**にする必要があったため、`showCardBack` を残す意味がなくなりました。

このため、**今回 `showCardBack` を削除し、`isEditing` フラグに集約**しました。  
この変更後、**FlipCard の表裏の挙動が正しく動作している**ことも確認済みです。

---

以上、よろしくお願いします。

2024-10-27 04:15 UTC, Ituking commented
@schwarzwald0906 @masa-tokyo 

Slackにて連携済みですが、証跡として対応した旨ここにも記載しておきます😃　

2024-10-27 12:08 UTC, masa-tokyo reviewed
@schwarzwald0906 

サーバー側のコメント一つしたので確認お願いします🙏

2024-10-27 12:08 UTC, masa-tokyo commented on lib/features/photo/photo_detail/widgets/photo_detail_card.dart
> +    return FlipCard(
@Ituking 

>実装上も、FlipCard の 表裏を常に切り替え可能な状態にする必要があったため、showCardBack を残す意味がなくなりました。

こちら、`showCardBack`がfalseの場合(PhotoのstoreIdがfirestore側でnull = 空文字の初期値のまま）にはそもそもフリップ不可能にする、という役割はあったはずなのですが、この仕様が以下のFigmaとは違う仕様になってしまっていますね、、

https://www.figma.com/design/9qlPzlsvF9CfYiYBED4yNR/My_Gourmet?node-id=2068-5813&node-type=frame&t=5tuMZjSW5nj4KvbN-0

storeIdが無い場合には、フリップは出来るものの「店舗未選択です」となっている想定のはずです。

@schwarzwald0906 
写真をスワイプへサーバー側へ送った後の挙動としての、以下`storeId`って現状は以下スキーマのようにnullではなくて何かしら`storeIds`内の値を入れているという感じなんでしたっけ？？

![CleanShot 2024-10-27 at 21 03 27@2x](https://github.com/user-attachments/assets/3d857a94-67c1-4efc-a6da-69ddb440872a)

2024-10-27 12:15 UTC, Ituking commented
@masa-tokyo 

なるほど。
確かに現在編集モードで、 FlipCardが表裏変更できることが確認できていますが、
showCardBackは消さない方が良いですかね？
もし不都合なら、showCardBackだけは戻した方が良いですよね？

2024-10-27 12:38 UTC, masa-tokyo commented
@Ituking 
いえ、元々の実装がFigmaの仕様と乖離してしまっていたので、カードは常にひっくり返せるようにこのままで大丈夫です！
これは今回のイツキングさんの対応箇所と直接は関係ないのですが、変更するべき点は、そもそもshowCardBackというプロパティ自体無くすべきという点ですね、！
金さんに質問していた点は、サーバー側の実装的に現状showCardBackがfalseになり得ないのであればそれで問題ないかなと！

2024-10-29 01:57 UTC, schwarzwald0906 commented
@masa-tokyo 
お疲れ様です。
これって今まさきさんのボール持ちという認識であっていますか？

2024-10-29 02:04 UTC, schwarzwald0906 commented
https://github.com/MyGourmet/My_Gourmet/pull/115#discussion_r1818074537
@masa-tokyo 
すみません、slackに通知が来てなくて気づきませんでした🙇
はい、先頭の値をstoreIdに設定するようになっています。ご指摘の通り、修正しないといけないです。

2024-10-29 13:15 UTC, masa-tokyo commented
@schwarzwald0906 

>はい、先頭の値をstoreIdに設定するようになっています。ご指摘の通り、修正しないといけないです。

なるほどです！
ただ、exifから情報取得出来なかった場合の考慮が抜けていたので、以下２パターンでの扱い検討必要かなと思いました。。！

i) 写真に緯度経度が無い場合
この場合はnullで返される認識であってますか、？
この場合は現状としては反転させないようにすべきですが（このPRが出る前の実装通り）、こちらの[GoogleMap導入の仕様](https://www.notion.so/masakisato/GoogleMap-63a1cbce837b478587c046d337b2d282?pvs=23)次第では反転させたところから店舗を紐付けられるようになりますよね

ii) ある場合

[こちらのコメント](https://github.com/MyGourmet/My_Gourmet/pull/115#discussion_r1818074537)で触れたように、「店舗未選択です」と表示したいのですが、i)を`storeId`がnullかどうかで判別するのであれば、別の判別の仕方が必要そうです。
i)の方が重要性高いのであれば、こちらはこのまま初期値を入れておく仕様（将来的にはAI使ってこの精度を上げたいはず）でも良いかもしれません🤔

2024-10-30 04:55 UTC, schwarzwald0906 commented
> @schwarzwald0906
> 
> > はい、先頭の値をstoreIdに設定するようになっています。ご指摘の通り、修正しないといけないです。
> 
> なるほどです！ ただ、exifから情報取得出来なかった場合の考慮が抜けていたので、以下２パターンでの扱い検討必要かなと思いました。。！
> 
> i) 写真に緯度経度が無い場合 この場合はnullで返される認識であってますか、？ この場合は現状としては反転させないようにすべきですが（このPRが出る前の実装通り）、こちらの[GoogleMap導入の仕様](https://www.notion.so/masakisato/GoogleMap-63a1cbce837b478587c046d337b2d282?pvs=23)次第では反転させたところから店舗を紐付けられるようになりますよね
> 
> ii) ある場合
> 
> [こちらのコメント](https://github.com/MyGourmet/My_Gourmet/pull/115#discussion_r1818074537)で触れたように、「店舗未選択です」と表示したいのですが、i)を`storeId`がnullかどうかで判別するのであれば、別の判別の仕方が必要そうです。 i)の方が重要性高いのであれば、こちらはこのまま初期値を入れておく仕様（将来的にはAI使ってこの精度を上げたいはず）でも良いかもしれません🤔

@masa-tokyo 
写真に緯度経度が無い場合は、areaStoreIds自体のフィールド自体が生成されません。

店舗が決定されたかどうかのフィールドをもう一つ追加して、そこで判定する、でいかがでしょうか？

あとすみません、こちらは、今Masakiさんのボール持ちということで認識あっていますか？
このステータスだと、Masakiさん待ちに見えます。
![CleanShot 2024-10-30 at 13 54 40](https://github.com/user-attachments/assets/16db23c2-1731-47d6-9371-fd556986c4d3)

2024-10-30 06:11 UTC, Ituking commented
> @schwarzwald0906
> 
> > はい、先頭の値をstoreIdに設定するようになっています。ご指摘の通り、修正しないといけないです。
> 
> なるほどです！ ただ、exifから情報取得出来なかった場合の考慮が抜けていたので、以下２パターンでの扱い検討必要かなと思いました。。！
> 
> i) 写真に緯度経度が無い場合 この場合はnullで返される認識であってますか、？ この場合は現状としては反転させないようにすべきですが（このPRが出る前の実装通り）、こちらの[GoogleMap導入の仕様](https://www.notion.so/masakisato/GoogleMap-63a1cbce837b478587c046d337b2d282?pvs=23)次第では反転させたところから店舗を紐付けられるようになりますよね
> 
> ii) ある場合
> 
> [こちらのコメント](https://github.com/MyGourmet/My_Gourmet/pull/115#discussion_r1818074537)で触れたように、「店舗未選択です」と表示したいのですが、i)を`storeId`がnullかどうかで判別するのであれば、別の判別の仕方が必要そうです。 i)の方が重要性高いのであれば、こちらはこのまま初期値を入れておく仕様（将来的にはAI使ってこの精度を上げたいはず）でも良いかもしれません🤔

@schwarzwald0906 @masa-tokyo 
この件、MasakiさんがOKならdevにマージして、
別タスクで新たに対応した方が良いのでは？とも思うのですが、認識違ってますかね？

2024-10-30 08:19 UTC, masa-tokyo reviewed
@schwarzwald0906 @Ituking 
>ただ、それは今回の内容と関係ないので、別タスクでお願いします。

こちらのメッセージ見逃していました🙏
別途切り分けた後のissueをこの直後に対応しないのであれば、`showCardBack`は一旦元のまま（緯度経度無くてfalseになる場合は裏返せない）にしておいた方が良いかと思います...！

2024-10-30 08:52 UTC, schwarzwald0906 commented
> @schwarzwald0906 @Ituking
> 
> > ただ、それは今回の内容と関係ないので、別タスクでお願いします。
> 
> こちらのメッセージ見逃していました🙏 別途切り分けた後のissueをこの直後に対応しないのであれば、`showCardBack`は一旦元のまま（緯度経度無くてfalseになる場合は裏返せない）にしておいた方が良いかと思います...！

@masa-tokyo 
お疲れさまです！このメッセージは僕宛てなのか、それともイツキングさん宛てでしょうか？

また、少し表現が難しいのですが、Masakiさんがスクラムマスターとして「これは別タスクで対応することを提案しつつ、タイミングが不明な場合はshowCardBackは元のままにする」といった形でハンドリングしていただくのも一つの方法かなと考えましたが、いかがでしょうか？

2024-10-30 10:14 UTC, masa-tokyo commented
@schwarzwald0906 
>お疲れさまです！このメッセージは僕宛てなのか、それともイツキングさん宛てでしょうか？

金さんのメッセージへの引用への返信 & 今回の別issueの優先度の判断を金さんに委ねるという意味合いで金さんにもメンションをつけてました、！
（金さん→イツキングさんの意味合いでしたがややこしくなってしまいすいません、）

>また、少し表現が難しいのですが、Masakiさんがスクラムマスターとして「これは別タスクで対応することとしつつ、タイミングが不明なので、showCardBackは元のままにしましょう」といった形でハンドリングしていただくのも一つの方法かなと考えましたが、いかがでしょうか？

現状「スクラムマスター」のような役割まで僕が負えるかはまた別途ご相談出来ればと思いますが、issue自体は細かく切り分ける方針でご提案していきますね🙏

@Ituking 
上記、金さん的には大丈夫のようなのでご変更お願いします！

2024-10-30 10:30 UTC, Ituking commented
> @schwarzwald0906
> 
> > お疲れさまです！このメッセージは僕宛てなのか、それともイツキングさん宛てでしょうか？
> 
> 金さんのメッセージへの引用への返信 & 今回の別issueの優先度の判断を金さんに委ねるという意味合いで金さんにもメンションをつけてました、！ （金さん→イツキングさんの意味合いでしたがややこしくなってしまいすいません、）
> 
> > また、少し表現が難しいのですが、Masakiさんがスクラムマスターとして「これは別タスクで対応することとしつつ、タイミングが不明なので、showCardBackは元のままにしましょう」といった形でハンドリングしていただくのも一つの方法かなと考えましたが、いかがでしょうか？
> 
> 現状「スクラムマスター」のような役割まで僕が負えるかはまた別途ご相談出来ればと思いますが、issue自体は細かく切り分ける方針でご提案していきますね🙏
> 
> @Ituking 上記、金さん的には大丈夫のようなのでご変更お願いします！

@masa-tokyo 
この件ですが、
「ご変更」というのはphoto_detail_card.dartのshowCardBackは元のままに戻しましょうという認識で良いですかね？
ちょっとよくわからなくなってきました。。。

2024-10-30 10:58 UTC, masa-tokyo commented
@Ituking 
>「ご変更」というのはphoto_detail_card.dartのshowCardBackは元のままに戻しましょうということで良いですかね？

はい、合っています！

2024-10-30 11:01 UTC, masa-tokyo requested changes
@Ituking 

>「ご変更」というのはphoto_detail_card.dartのshowCardBackは元のままに戻しましょうということで良いですかね？

はい、合っています！

2024-11-01 01:58 UTC, Ituking commented
@masa-tokyo 
photo_detail_card.dartのshowCardBackは元のままに戻したので、確認お願いします！

2024-11-02 13:19 UTC, schwarzwald0906 commented
@masa-tokyo 
お疲れ様です！
いまハッカソンでお忙しいと思うので、一旦マージしてもいいですか？

2024-11-02 13:25 UTC, masa-tokyo approved these changes
@Ituking 

確認遅くなりすみません！
LGTMです！
[![LGTMeow](https://lgtm-images.lgtmeow.com/2024/02/05/10/a51a92bd-fd94-44db-99bb-c2e130c77613.webp)](https://lgtmeow.com)

2024-11-03 01:15 UTC, merged