[TAS-219] iOSビルド高速化：Podfile最適化とプロジェクト設定の調整
MyGourmet/My_Gourmet pull request #122
Opened 2024-11-07 15:10 UTC by Ituking

## 関連のタスク issue

https://www.notion.so/masakisato/ios-Build-firestore-2d878e41b0c44f7793da55a66de6f68e

## 対応したこと

- iOSビルド時間短縮のため、Podfileの最適化とプロジェクト設定の修正
- iOSのビルドキャッシュ設定の調整（Podfile.lock の再生成）

## 未解決事項
  

- なし

## 実際の挙動
  
- UIに影響はないため、特にスクリーンショットは無し

## チェックリスト
  
- [x] 実装完了後、問題が起こっていないか実際に動作確認したか  
- [x] 補足があった方が良い/重点的にレビューが欲しい箇所にGitHub上でコメントをしたか

## その他コメント

- この修正でiOSビルド時間が改善されることを確認しました。
- この修正でCIやシミュレーターでのビルド時間が早くなることが期待されます。

2024-11-07 15:41 UTC, Ituking commented
## 競合解消に関する情報

このプルリクエストでは、`feature/ios-build-speed-improvement` ブランチと `dev` ブランチの間で `Podfile.lock` に競合が発生していました。

主な競合箇所は以下の通りです：

1. **COCOAPODS のバージョン**
   - `feature/ios-build-speed-improvement` ブランチでは `1.16.1` が指定されていた一方、`dev` ブランチでは `1.16.2` が指定されていたため、最新のバージョン `1.16.2` を採用しました。

2. **BoringSSL-GRPC の依存関係**
   - `dev` ブランチで `BoringSSL-GRPC` の依存関係が追加されていたため、その依存関係とチェックサムを保持しました。

以上の対応により、競合は解消されています。

2024-11-07 23:27 UTC, masa-tokyo requested changes
@Ituking 

ご対応ありがとうございます！
コメントご確認お願いします！

2024-11-08 00:28 UTC, Ituking commented on ios/Podfile.lock
@masa-tokyo 
`Podfile.lock` は削除されていません。
競合解消後に再生成したファイルが正常にコミットされ、
リモートリポジトリにも反映されています。
`git status` でも変更が検知されていないため、最新状態であることを確認済みです。

2024-11-08 01:34 UTC, masa-tokyo approved these changes
@Ituking 

ありがとうございます！
LGTMです！
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/03/02/10/0a70bef2-b7af-409f-a78c-c7b702ed2be3.webp)](https://lgtmeow.com)

2024-11-08 01:34 UTC, masa-tokyo commented on ios/Podfile.lock
@Ituking 

すいません、見間違いでした🙇‍♂️

2024-11-09 08:35 UTC, merged